### ISSUE TITLE
demande d'ajout : pouvoir créer des gabarits et fonction copie

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/domains#10]
Bonjour
Première demande : 
dans le plugin version 1.8.0 pour GLPI 9.1, il n'est pas possible de créer des gabarits, serait-il possible d'ajouter cette fonctionnalité ?

2e demande : 
Quand on est dans la liste des domaines,  il n'est pas possible de faire des copier de domaines en les sélectionnant et en faisant "Actions -> Copier". Pouvez-vous l'ajouter ?

Merci

**Comment by amma35** [comment]
For plugin evolutions (templates), it is necessary to go through a specific development that we realize for our customers.
