### ISSUE TITLE
bug dans Domains 1.8.0 pour GLPI 9.1

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/domains#12]
Bonjour

Quand on a déjà créé un domaine, qu'on en créé un nouveau et que le système propose dans les dates de création et d'expiration sur les dates déjà saisies, si on en sélectionne une, la date s'inscrit dans le champ mais quand on fait "Ajouter" pour créer le domaine, les dates ont disparu, Seule la date du jour apparaît dans le champ "date de création".

Par contre, si on fait un copier coller puis Ajouter, là ça fonctionne, les dates sont conservées

Merci d'avance

**Comment by amma35** [comment]
Bonjour,

Je n'arrive pas à répliquer votre problématique.

Quel navigateur utilisez-vous ?

**Comment by sebfun** [comment]
Firefox 49 puis 50

**Comment by sebfun** [comment]
j'ai migré vers GLPI 9.1.1 cela me le fait quand même

**Comment by amma35** [comment]
Avez-vous des logs dans les fichiers glpi/files/_logs/php-errors.log et sql-errors.log ? 
Pouvez-vous essayer avec la nouvelle release aussi (https://github.com/InfotelGLPI/domains/releases/tag/1.8.1) ?

**Comment by sebfun** [comment]
non pas de log je les avais supprimé 
Je suis passé en GLPI 9.1.2 du coup... j'essayerais votre nouvelle version
