### ISSUE TITLE
suppliers dont work

### ISSUE THREAD

**Issue by HelpITru** [InfotelGLPI/domains#13]
Hello !

- DOMAINS plugin ver 1.8.0
- GLPI ver 9.1 (and 9.1.1)
- when I enable this plugin I see this bug https://github.com/glpi-project/glpi/issues/1311 and when I disable plugin DOMAINS everything work fine and correct ! 

Thanks !

**Comment by amma35** [comment]
Have you errors in apache or glpi logs ?

**Comment by HelpITru** [comment]
[Tue Dec 20 22:05:12 2016] [error] [client 127.0.0.1] PHP Fatal error:  Call to a member function fetch_assoc() on a non-object in /opt/glpi-0.84.5/inc/dbmysql.class.php on line 308, referer: https://it.helpit.ru/glpi/front/supplier.form.php?id=2

**Comment by HelpITru** [comment]
its from apache log

**Comment by amma35** [comment]
Can you give me the contents of the file : glpi-0.84.5/files/_log/sql-errors.log

**Comment by HelpITru** [comment]
in attach

**Comment by amma35** [comment]
I do not replicate the bug.

Can you provide me with the glpi-0.84.5/plugins/domains/inc/domain.class.php file because this error comes from this file.

**Comment by HelpITru** [comment]
The same bug with 9.1.1 glpi release 
Please fix

**Comment by amma35** [comment]
New release : https://github.com/InfotelGLPI/domains/releases/tag/1.8.1
