### ISSUE TITLE
cannot edit a supplier when the plugin Domains is enabled

### ISSUE THREAD

**Issue by btry** [InfotelGLPI/domains#14]
Hi I report here an issue opened for the plugin Orders.

The user reported he solved himself his problem thanks to a post in the forum. He applied a fix found on the forum.

https://github.com/pluginsGLPI/order/issues/109#issuecomment-284846407

http://forum.glpi-project.org/viewtopic.php?pid=173454#p173454

I also wonder if this applies to #13. Being not sure, I preferred create a new issue.

**Comment by amma35** [comment]
Indeed, this fix corrects the bug.
I'll correct that.
Thank you

**Comment by HelpITru** [comment]
I upgrade to 9.1.1 and the same bug open
