### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by hduble** [InfotelGLPI/domains#15]
Bonjour,

Les "notes" ne sont pas disponible dans le plugin, alors que le code semble l'implémenter, y a t'il un paramétrage spécifique à faire ?

Cdt
H Dublé

**Comment by amma35** [comment]
Bonjour,

Il faut bien ajouter dans le profil la lecture des notes et la mise à jour pour le plugin Domain.

![note](https://cloud.githubusercontent.com/assets/15138371/25267170/131faad6-2674-11e7-8a83-217ea7241af0.png)

**Comment by hduble** [comment]
Super, ca fonctionne !
