### ISSUE TITLE
feature request "price" and "direct link"

### ISSUE THREAD

**Issue by da-sti** [InfotelGLPI/domains#16]
thanks for this great job, very useful plugin !!

2 suggestions that could be useful for people handeling numerous domains/registrar

1/
add a field "price" (for now I personally use the comment field) that can be visible from the global list

2/
add a field "url direct access" that is also visible in the domains list that can allow to access the admin console in one click

**Comment by C-Duv** [comment]
You might want to try the plugin "fields" which have an "URL" field type.

**Comment by amma35** [comment]
For plugin evolutions, it is necessary to go through a specific development that we realize for our customers.
