### ISSUE TITLE
feature request assing group to Domain

### ISSUE THREAD

**Issue by L0rz** [InfotelGLPI/domains#21]
Is it possible to add a manager Group?
------------
* Version of the plugin : 

2.0.1
* Version of your GLPI : 
9.3

* Steps to reproduce (which actions have you made) :

* Expected result :

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by amma35** [comment]
Hi,
There is already the possibility to assign a group to a domain
