### ISSUE TITLE
Expiring domains notification

### ISSUE THREAD

**Issue by tomSDL** [InfotelGLPI/domains#24]
Hi,

Email notification list domains expiring up to 5/6 months in advance.

How can I change this to only notify domains expiring in 1 month?

Thanks,

**Comment by 27lab** [comment]
Hi,

I got the same question, where can we change the number of month before we got the mail of expiration ?

Thanks in advance,

**Comment by AHinMaine** [comment]
It looks like it's configured under Setup &rarr; Automatic Actions &rarr; DomainsAlert &rarr; Plugin Setup.

**Comment by ales-infotel** [comment]
@AHinMaine  have the answer
