### ISSUE TITLE
2.2.0 packaged version identifies as 2.1.0

### ISSUE THREAD

**Issue by ggarrard** [InfotelGLPI/domains#27]
* Version of the plugin :  2.2.0

* Version of your GLPI :  9.5.1

* Steps to reproduce (which actions have you made) : fresh install of glpi-domains-2.2.0.tar.gz

* Expected result : domains 2.2.0 version installed

* Actual result : version installed is identified as 2.1.0

* URL of the page :

* Screenshot of the problem (if pertinent) :

The PLUGIN_DOMAINS_VERSION was not updated in setup.php.

**Comment by keha35** [comment]
Hello,

Thanks for reporting the issue.
I've create a new release with the fix.
