### ISSUE TITLE
Migrate to GLPI Domains

### ISSUE THREAD

**Issue by hgpit** [InfotelGLPI/domains#28]
Hello,

We have just upgraded our GLPI 9.4.6 to 9.5.1.

As 'domains' is now a core feature of GLPI (Management...Domains), we would rather use this new built-in functionality.
However we have lots of domains entered under the plugin (Assets...Domains).

Is there a migration tool, to move/copy all plugin Domains to core Domains? Or does anyone have some handy SQL which would do it?

P.S. We upgraded the domains plugin to v2.2.1 (manually), but the GLPI plugin manager still alerts us that v2.1.0 is installed and v2.2.1 is available.

Thanks

**Comment by tsmr** [comment]
Hello. The core team has developed a migration script with glpi console :
php bin/console glpi:migration:domains_plugin_to_core
