### ISSUE TITLE
Demande de fonction (Ajouter des année sur plusieurs domaines)

### ISSUE THREAD

**Issue by jckubiaczyk** [InfotelGLPI/domains#3]
Bonjour,

Serait il possible d'ajouter une fonction pour rajouter 1,2 ... ans a une liste de domaine chez un fournisseur spécifique.

Ci-joint la commande MySQL :
UPDATE `glpi_plugin_domains_domains` 
SET `date_expiration` = DATE_ADD(`date_expiration`, INTERVAL 1 YEAR)
WHERE  `suppliers_id` = 1;

Merci d'avance

**Comment by keha35** [comment]
For plugin evolutions, it is necessary to go through a specific development that we realize for our customers.
